USE CLINICA_ODONTOLOGICA;

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'1',	'1',	'2019-10-28 16:00:00',	'SIM',	'NAO',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'2',	'1',	'2019-10-30 16:00:00',	'SIM',	'NAO',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'3',	'2',	'2019-11-02 16:00:00',	'SIM',	'NAO',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'4',	'2',	'2019-11-18 10:00:00',	'NAO',	'NAO',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'5',	'3',	'2019-11-19 14:00:00',	'SIM',	'NAO',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'6',	'3',	'2019-02-01 16:00:00',	'SIM',	'SIM',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'7',	'4',	'2019-11-05 09:00:00',	'SIM',	'SIM',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'8',	'4',	'2019-11-02 17:00:00',	'NAO',	'NAO',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'9',	'10',	'2019-06-06 15:00:00',	'NAO',	'SIM',	NULL
);

INSERT INTO RELATORIO_DE_CONSULTAS(
ID_CONSULTA,ID_PRONTUARIO,DATA_HORA,DENTISTA_ASSINOU,PACIENTE_ASSINOU,DESCRICAO)
VALUES(
'10',	'10',	'2019-11-04 16:00:00',	'SIM',	'NAO',	NULL
);

SELECT * FROM RELATORIO_DE_CONSULTAS;