USE CLINICA_ODONTOLOGICA;

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'1',		'1',	'1',	NULL,	'1',	'OBTURAÇÃO',		'EM ANDAMENTO',		'2019-10-28',	NULL,			'150'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'2',		'1',	NULL,	NULL,	'2',	'LIMPEZA',		'EM ANDAMENTO',		'2019-10-30',	NULL,			'90'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'3',		'1',	NULL,	NULL,	'3',	'LIMPEZA',		'EM ANDAMENTO',		'2019-11-02',	NULL,			'120'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(	
'4',		'2',	'2',	NULL,	'4',	'CLAREAMENTO',	'EM ANDAMENTO',		'2019-11-18',	'2020-03-01',	'240'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'5',		'2',	NULL,	'5',	'5',	'LIMPEZA',		'EM ANDAMENTO',		'2019-11-19',	NULL,			'50'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'6',		'2',	NULL,	'6',	'5',	'CLAREAMENTO',	'EM ANDAMENTO',		'2019-02-01',	'2019-12-01',	'360'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'7',		'10',	'1',	'7',	'7',	'OBTURAÇÃO',		'EM ANDAMENTO',		'2019-11-05',	NULL,			'120'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'8',		'10',	'7',	'3',	'7',	'LIMPEZA',		'CONCLUIDO',		'2019-06-06',	NULL,			'60'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'9',		'9',	'5',	NULL,	'7',	'OBTURAÇÃO',		'EM ANDAMENTO',		'2019-12-06',	NULL,			'100'
);

INSERT INTO TRATAMENTO(
ID_TRATAMENTO,ID_PRONTUARIO,TECNO,AUXNO,DENTNO,NOME,ESTADO,DATA_INICIO,DATA_FIM,VALOR)
VALUES(
'10',		'8',	NULL,	NULL,	'8',	'LIMPEZA',		'CONCLUIDO',		'2019-02-04',	NULL,			'80'
);

SELECT * FROM TRATAMENTO;