USE CLINICA_ODONTOLOGICA;

CREATE TABLE TECNICO
(TECNO CHAR(6) PRIMARY KEY NOT NULL,
NOME VARCHAR(40) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
SALARIO FLOAT(8) NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
DATA_NASCIMENTO DATE,
DDD CHAR(2),
TELEFONE CHAR(9),
CRO_TSB CHAR (20) NOT NULL
);

CREATE TABLE AUXILIAR
(AUXNO CHAR(6) PRIMARY KEY NOT NULL,
NOME VARCHAR(40) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
SALARIO FLOAT(8) NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
DDD CHAR(2),
TELEFONE CHAR(9)
);

CREATE TABLE DENTISTA
(DENTNO CHAR(6) PRIMARY KEY NOT NULL,
NOME VARCHAR(40) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
SALARIO FLOAT(8) NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
DATA_NASCIMENTO DATE,
DDD CHAR(2),
TELEFONE CHAR(9),
CRO_DENTISTA CHAR (20) NOT NULL
);

CREATE TABLE TRATAMENTO
(ID_TRATAMENTO CHAR(6) PRIMARY KEY NOT NULL,
ID_PRONTUARIO CHAR(6) NOT NULL,
TECNO CHAR(6),
AUXNO CHAR(6),
DENTNO CHAR(6) NOT NULL,
NOME VARCHAR(40) NOT NULL,
ESTADO CHAR(20) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE,
VALOR FLOAT(8) NOT NULL
);

CREATE TABLE PAGAMENTO
(ID_PAGAMENTO CHAR(6) PRIMARY KEY NOT NULL,
ID_PRONTUARIO CHAR(6) NOT NULL,
NOME_PACIENTE VARCHAR(40) NOT NULL,
TIPO CHAR(8) NOT NULL,
QTD_PARCELAS SMALLINT NOT NULL,
ESTADO CHAR(20) NOT NULL,
VALOR FLOAT(8) NOT NULL
);

CREATE TABLE AGENDA
(ID_AGENDA CHAR(6) PRIMARY KEY NOT NULL,
ID_PACIENTE CHAR(6) NOT NULL,
DATA_HORARIO TIMESTAMP NOT NULL,
ESTADO CHAR(20) NOT NULL
);

CREATE TABLE PACIENTE
(ID_PACIENTE CHAR(6) PRIMARY KEY NOT NULL,
NOME VARCHAR(40) NOT NULL,
SEXO CHAR(1) NOT NULL,
DATA_NASCIMENTO DATE,
CPF CHAR(11) UNIQUE NOT NULL,
DDD CHAR(2),
TELEFONE CHAR(9),
ENDERECO VARCHAR(40),
PLANO_DE_SAUDE VARCHAR(40)
);

CREATE TABLE RELATORIO_DE_CONSULTAS
(ID_CONSULTA CHAR(6) PRIMARY KEY NOT NULL,
ID_PRONTUARIO CHAR(6) NOT NULL,
DATA_HORA TIMESTAMP NOT NULL,
DENTISTA_ASSINOU CHAR(3) NOT NULL,
PACIENTE_ASSINOU CHAR(3) NOT NULL,
DESCRICAO VARCHAR(100)
);

CREATE TABLE PRONTUARIO
(ID_PRONTUARIO CHAR(6) PRIMARY KEY NOT NULL,
ID_PACIENTE CHAR(6) UNIQUE NOT NULL,
DATA_HORA_ENTRADA TIMESTAMP NOT NULL,
ESTADO CHAR(20) NOT NULL
);