USE CLINICA_ODONTOLOGICA;

ALTER TABLE PRONTUARIO
ADD CONSTRAINT FK_PRONTUARIO_PACIENTE
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
ON DELETE CASCADE;

ALTER TABLE AGENDA
ADD CONSTRAINT FK_AGENDA_PACIENTE
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE RELATORIO_DE_CONSULTAS
ADD CONSTRAINT FK_ID_RELATORIO_PRONTUARIO
FOREIGN KEY (ID_PRONTUARIO) REFERENCES PRONTUARIO(ID_PRONTUARIO);

ALTER TABLE PAGAMENTO
ADD CONSTRAINT FK_PAGAMENTO_PRONTUARIO
FOREIGN KEY (ID_PRONTUARIO) REFERENCES  PRONTUARIO(ID_PRONTUARIO);

ALTER TABLE TRATAMENTO
ADD CONSTRAINT FK_TRATAMENTO_PRONTUARIO
FOREIGN KEY (ID_PRONTUARIO) REFERENCES PRONTUARIO(ID_PRONTUARIO);

ALTER TABLE TRATAMENTO
ADD CONSTRAINT FK_TRATAMENTO_TECNICO
FOREIGN KEY (TECNO) REFERENCES TECNICO(TECNO);

ALTER TABLE TRATAMENTO
ADD CONSTRAINT FK_TRATAMENTO_AUXILIAR
FOREIGN KEY (AUXNO) REFERENCES AUXILIAR(AUXNO);

ALTER TABLE TRATAMENTO
ADD CONSTRAINT FK_TRATAMENTO_DENTISTA
FOREIGN KEY (DENTNO) REFERENCES DENTISTA(DENTNO);

